// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedSocial.BD.Data;

#nullable disable

namespace RedSocial.BD.Migrations
{
    [DbContext(typeof(BDContext))]
    [Migration("20221109123804_Coreccion")]
    partial class Coreccion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RedSocial.BD.Data.Entidades.EntidadEstadistica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Ganadas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Horas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JuegoProfesional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MVP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MayorLogro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEquipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartidasJugadas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perdidas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosicionMundial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosicionPaisNatal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empatadas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex(new[] { "id" }, "IdEstadistica_UQ")
                        .IsUnique();

                    b.ToTable("TablaEEntidad");
                });

            modelBuilder.Entity("RedSocial.BD.Data.Entidades.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContenidoPublicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsPrivada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MeGusta")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("VecesCompartido")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex(new[] { "Id" }, "IdUsuario_UQ")
                        .IsUnique();

                    b.ToTable("TablaPublicacion");
                });

            modelBuilder.Entity("RedSocial.BD.Data.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgPortada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "IdUsuario_UQ")
                        .IsUnique()
                        .HasDatabaseName("IdUsuario_UQ1");

                    b.ToTable("TablaUsuario");
                });

            modelBuilder.Entity("RedSocial.BD.Data.Entidades.Publicacion", b =>
                {
                    b.HasOne("RedSocial.BD.Data.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
